package tr.com.uslanozan.evritext.captions

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.StreamInfo

/**
 * Caption discovery and download — the Kotlin side of `phase0/evri/captions.py`.
 *
 * Phase 0 used yt-dlp because it already solves poToken/nsig; on-device that job
 * falls to NewPipeExtractor, which is the accepted cost of not shipping a backend
 * (DESIGN.md R2).
 */
class CaptionSource(
    private val http: OkHttpClient = OkHttpClient(),
) {

    data class Track(
        val languageTag: String,
        val displayName: String,
        val url: String,
        val autoGenerated: Boolean,
        val format: String,
    ) {
        /** "en-GB" and "en" are the same language for our purposes. */
        val baseLanguage: String get() = languageTag.substringBefore('-').lowercase()
    }

    data class VideoCaptions(
        val videoId: String,
        val title: String,
        val durationS: Double,
        val tracks: List<Track>,
    ) {
        /**
         * Priority from DESIGN.md 2.3: a human-written track in a preferred language
         * beats an automatic one, and anything beats nothing.
         */
        fun best(preferred: List<String> = DEFAULT_PREFERRED): Track? {
            val (manual, automatic) = tracks.partition { !it.autoGenerated }
            for (pool in listOf(manual, automatic)) {
                for (language in preferred) {
                    pool.firstOrNull { it.languageTag.equals(language, ignoreCase = true) }
                        ?.let { return it }
                }
                for (language in preferred) {
                    val base = language.substringBefore('-').lowercase()
                    pool.firstOrNull { it.baseLanguage == base }?.let { return it }
                }
            }
            return null
        }

        /** A human-written track already in the target language: do nothing at all. */
        fun manualIn(language: String): Track? {
            val base = language.substringBefore('-').lowercase()
            return tracks.firstOrNull { !it.autoGenerated && it.baseLanguage == base }
        }

        /**
         * An automatic track in [language], which means the video is *spoken* in it.
         *
         * YouTube runs speech recognition only in the language being spoken; tracks in
         * other languages are translations of that one. So an auto track in Turkish is
         * the strongest signal available that this is a Turkish video.
         */
        fun spokenIn(language: String): Track? {
            val base = language.substringBefore('-').lowercase()
            return tracks.firstOrNull { it.autoGenerated && it.baseLanguage == base }
        }
    }

    suspend fun probe(videoId: String): VideoCaptions = withContext(Dispatchers.IO) {
        ensureInitialised()
        val info = StreamInfo.getInfo(ServiceList.YouTube, watchUrl(videoId))
        val tracks = info.subtitles.orEmpty().map { stream ->
            Track(
                languageTag = stream.languageTag ?: "",
                displayName = stream.displayLanguageName ?: stream.languageTag.orEmpty(),
                url = stream.content ?: "",
                autoGenerated = stream.isAutoGenerated,
                format = stream.format?.getName().orEmpty(),
            )
        }.filter { it.url.isNotBlank() }

        Log.i(
            TAG,
            "${info.id}: ${tracks.size} track(s) — " +
                tracks.joinToString { "${it.languageTag}${if (it.autoGenerated) "(auto)" else ""}" },
        )

        VideoCaptions(
            videoId = info.id.orEmpty(),
            title = info.name.orEmpty(),
            durationS = info.duration.toDouble(),
            tracks = tracks,
        )
    }

    /**
     * Fetches the track as WebVTT.
     *
     * NewPipe hands back a `timedtext` URL already carrying `fmt=ttml`, so the format
     * has to be *replaced* rather than appended — asking for vtt keeps the parser the
     * same one Phase 0 validated.
     */
    suspend fun download(track: Track): String = withContext(Dispatchers.IO) {
        val url = track.url.toHttpUrl().newBuilder()
            .removeAllQueryParameters("fmt")
            .addQueryParameter("fmt", "vtt")
            .build()
        val request = Request.Builder().url(url).build()
        http.newCall(request).execute().use { response ->
            check(response.isSuccessful) { "caption download failed: HTTP ${response.code}" }
            response.body?.string().orEmpty()
        }
    }

    private fun ensureInitialised() {
        synchronized(LOCK) {
            if (NewPipe.getDownloader() == null) {
                NewPipe.init(OkHttpDownloader())
            }
        }
    }

    companion object {
        private const val TAG = "CaptionSource"
        private val LOCK = Any()

        val DEFAULT_PREFERRED = listOf("en", "en-orig", "en-US", "en-GB")

        fun watchUrl(videoId: String) = "https://www.youtube.com/watch?v=$videoId"
    }
}
