package tr.com.uslanozan.evritext.captions

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Which track we pick, and when we decide to do nothing at all.
 *
 * Doing nothing is the half that is easy to get wrong and impossible to notice in
 * testing on English videos: the symptom only appears when someone in the house puts
 * on a Turkish video and gets a machine paraphrase of speech they already understand.
 */
class TrackSelectionTest {

    private fun track(lang: String, auto: Boolean) = CaptionSource.Track(
        languageTag = lang,
        displayName = lang,
        url = "https://example.invalid/$lang",
        autoGenerated = auto,
        format = "vtt",
    )

    private fun video(vararg tracks: CaptionSource.Track) = CaptionSource.VideoCaptions(
        videoId = "test",
        title = "test",
        durationS = 600.0,
        tracks = tracks.toList(),
    )

    @Test
    fun `prefers a human-written English track over the automatic one`() {
        val video = video(track("en", auto = true), track("en", auto = false))
        assertEquals(false, video.best()!!.autoGenerated)
    }

    @Test
    fun `falls back to automatic when nobody wrote one`() {
        val video = video(track("en", auto = true))
        assertEquals(true, video.best()!!.autoGenerated)
    }

    @Test
    fun `matches a regional variant of the preferred language`() {
        val video = video(track("en-GB", auto = false))
        assertEquals("en-GB", video.best()!!.languageTag)
    }

    @Test
    fun `an automatic Turkish track means the video is spoken in Turkish`() {
        // The case this rule exists for: a Turkish video, where the right move is to
        // leave it alone rather than translate Turkish into Turkish.
        val video = video(track("tr", auto = true))
        assertNotNull(video.spokenIn("tr"))
    }

    @Test
    fun `a translated Turkish track does not mean the video is Turkish`() {
        // YouTube only runs recognition in the spoken language, so a *written* Turkish
        // track on an English video is a translation and must not stand us down.
        val video = video(track("en", auto = true), track("tr", auto = false))

        assertNull("a written track is not evidence of the spoken language", video.spokenIn("tr"))
        // It is still a reason to do nothing — a human already translated it.
        assertNotNull(video.manualIn("tr"))
    }

    @Test
    fun `an English video with no Turkish anywhere is ours to translate`() {
        val video = video(track("en", auto = true))

        assertNull(video.manualIn("tr"))
        assertNull(video.spokenIn("tr"))
        assertNotNull(video.best())
    }

    @Test
    fun `a video with no usable track at all`() {
        val video = video(track("de", auto = true), track("fr", auto = true))
        assertNull("German and French are not in the preferred list", video.best())
    }
}
