package tr.com.uslanozan.evritext.captions

import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Hits the live service on purpose.
 *
 * NewPipeExtractor's whole job is to keep up with a site that changes without
 * notice, so a test with a recorded fixture would pass forever while the real thing
 * broke. This is the one place where talking to the network is the point (DESIGN.md
 * R2), which is also why it is not part of any automated gate.
 */
class CaptionSourceTest {

    @Test
    fun `finds caption tracks for a video with auto captions`() = runBlocking {
        val result = CaptionSource().probe(BIG_STAN)

        println("video   ${result.videoId}  \"${result.title}\"  ${result.durationS}s")
        result.tracks.forEach {
            println("  ${it.languageTag.padEnd(8)} auto=${it.autoGenerated} ${it.format} ${it.url.take(70)}")
        }

        val best = result.best()
        println("best    ${best?.languageTag} auto=${best?.autoGenerated}")
        println("manual tr already present: ${result.manualIn("tr") != null}")

        assertTrue("no caption tracks found", result.tracks.isNotEmpty())
        assertTrue("no usable English track", best != null)
    }

    @Test
    fun `downloads the chosen track`() = runBlocking {
        val source = CaptionSource()
        val track = source.probe(BIG_STAN).best()
        requireNotNull(track) { "no track to download" }

        val body = source.download(track)
        println("downloaded ${body.length} chars, first 300:")
        println(body.take(300))

        assertTrue("body is not WebVTT", body.trimStart().startsWith("WEBVTT"))
    }

    private companion object {
        /** The 98-minute film Phase 0 measured everything against. */
        const val BIG_STAN = "sx8pViXxZQg"
    }
}
