package tr.com.uslanozan.evritext.subtitles

import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import tr.com.uslanozan.evritext.captions.CaptionSource
import tr.com.uslanozan.evritext.translate.GeminiTranslationProvider
import tr.com.uslanozan.evritext.translate.TranslationContext
import java.io.File

/** Manual end-to-end subtitle export for watching the segmenter output in VLC. */
class VlcSubtitlePreviewTest {

    @Test
    fun `creates old and resegmented Turkish subtitles for VLC`() = runBlocking {
        assumeTrue(
            "manual VLC preview — run with -PvlcPreview=true",
            System.getProperty("evritext.vlcPreview") == "true",
        )
        val root = findProjectRoot()
        val apiKey = findApiKey(root)
        assumeTrue("no GEMINI_API_KEY or root .env — skipping", apiKey != null)

        val mediaDir = File(root, "test-media")
        val spec = when (System.getProperty("evritext.vlcMovie")) {
            "sintel" -> PreviewSpec("Sintel", "sintel", sourceFile = "sintel.en.srt")
            "youtube-sample" -> PreviewSpec(
                title = "YouTube WO6aRHKe7_c",
                outputPrefix = "youtube-WO6aRHKe7_c",
                videoId = "WO6aRHKe7_c",
            )
            else -> PreviewSpec(
                "Tears of Steel",
                "tears-of-steel",
                sourceFile = "tears-of-steel.en.srt",
            )
        }
        val source = if (spec.videoId != null) {
            val captionSource = CaptionSource()
            val info = captionSource.probe(spec.videoId)
            val track = requireNotNull(info.best()) { "No usable captions for ${spec.videoId}" }
            println("Using ${track.languageTag} auto=${track.autoGenerated} captions for ${info.title}")
            SubtitleInput(captionSource.download(track), info.title, track.baseLanguage)
        } else {
            val sourceFile = File(mediaDir, requireNotNull(spec.sourceFile))
            require(sourceFile.isFile) { "Missing ${sourceFile.absolutePath}" }
            SubtitleInput(sourceFile.readText(Charsets.UTF_8), spec.title, "en")
        }

        val sentences = Sentences.merge(Vtt.load(source.content))
        val provider = GeminiTranslationProvider(apiKey!!)
        val translations = mutableListOf<String>()

        sentences.chunked(BATCH_SIZE).forEachIndexed { batchIndex, batch ->
            val start = batchIndex * BATCH_SIZE
            translations += provider.translate(
                sentences = batch.map(Sentence::text),
                sourceLang = source.language,
                targetLang = "tr",
                context = TranslationContext(
                    videoTitle = source.title,
                    before = sentences.subList((start - CONTEXT_SIZE).coerceAtLeast(0), start)
                        .map(Sentence::text),
                    after = sentences.drop(start + batch.size).take(CONTEXT_SIZE)
                        .map(Sentence::text),
                ),
            )
            println("Translated ${translations.size}/${sentences.size} sentences")
        }
        assertEquals(sentences.size, translations.size)

        val oldCues = sentences.zip(translations).map { (sentence, text) ->
            Cue(sentence.startMs, sentence.endMs, text)
        }
        val newCues = Sentences.toCues(sentences, translations)
        val oldFile = File(mediaDir, "${spec.outputPrefix}.old.tr.srt")
        val newFile = File(mediaDir, "${spec.outputPrefix}.new.tr.srt")
        oldFile.writeText(toSrt(oldCues), Charsets.UTF_8)
        newFile.writeText(toSrt(newCues), Charsets.UTF_8)

        val splitSentences = sentences.zip(translations).filter { (sentence, translation) ->
            TargetCueSegmenter.segment(sentence, translation).size > 1
        }
        println("Created ${oldFile.absolutePath} (${oldCues.size} cues)")
        println("Created ${newFile.absolutePath} (${newCues.size} cues)")
        println("Resegmented ${splitSentences.size}/${sentences.size} sentences at:")
        println(splitSentences.joinToString(", ") { (sentence, _) -> clock(sentence.startMs) })

        assertTrue("generated preview subtitle is empty", newCues.isNotEmpty())
    }

    private fun toSrt(cues: List<Cue>): String = buildString {
        cues.forEachIndexed { index, cue ->
            appendLine(index + 1)
            append(Vtt.formatTimestamp(cue.startMs))
            append(" --> ")
            appendLine(Vtt.formatTimestamp(cue.endMs))
            appendLine(cue.text)
            appendLine()
        }
    }

    private fun clock(ms: Long): String {
        val totalSeconds = ms / 1000
        return "%02d:%02d".format(totalSeconds / 60, totalSeconds % 60)
    }

    private fun findProjectRoot(): File {
        var dir: File? = File("").absoluteFile
        repeat(6) {
            if (File(dir, "settings.gradle.kts").isFile) return dir!!
            dir = dir?.parentFile
        }
        error("Project root not found")
    }

    private fun findApiKey(root: File): String? {
        System.getenv("GEMINI_API_KEY")?.trim()?.takeIf(String::isNotEmpty)?.let { return it }
        return File(root, ".env").takeIf(File::isFile)?.readLines()
            ?.firstOrNull { it.startsWith("GEMINI_API_KEY=") }
            ?.substringAfter('=')?.trim()?.takeIf(String::isNotEmpty)
    }

    private companion object {
        const val BATCH_SIZE = 30
        const val CONTEXT_SIZE = 3
    }

    private data class PreviewSpec(
        val title: String,
        val outputPrefix: String,
        val sourceFile: String? = null,
        val videoId: String? = null,
    )

    private data class SubtitleInput(
        val content: String,
        val title: String,
        val language: String,
    )
}
